"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

environ.Env.read_env(BASE_DIR.parent / ".env")


SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=[],
)

# ---------------------------------------------------------------------------
# Production security
# ---------------------------------------------------------------------------

SECURE_SSL_REDIRECT = env.bool(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=False,
)

SESSION_COOKIE_SECURE = env.bool(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=False,
)

CSRF_COOKIE_SECURE = env.bool(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=False,
)

SECURE_HSTS_SECONDS = env.int(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=0,
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
)

SECURE_HSTS_PRELOAD = env.bool(
    "DJANGO_SECURE_HSTS_PRELOAD",
    default=False,
)

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


# ---------------------------------------------------------------------------
# JWT
# ---------------------------------------------------------------------------

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "core",
    "accounts",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "conversations",
    "ai",
    "knowledge",
    "corsheaders",
    "storages",
]


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]


ROOT_URLCONF = "config.urls"


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

DATABASES = {
    "default": env.db(
        default=(
            f"postgresql://"
            f"{env('POSTGRES_USER')}:"
            f"{env('POSTGRES_PASSWORD')}@"
            f"{env('POSTGRES_HOST')}:"
            f"{env('POSTGRES_PORT')}/"
            f"{env('POSTGRES_DB')}"
        )
    )
}

# Keep PostgreSQL connections alive between requests.
#
# This is important for OmniChat because every chat request performs
# multiple database operations:
#
#   conversation/history lookup
#       -> document retrieval
#       -> message persistence
#       -> source persistence
#
# Without persistent connections, Django can repeatedly pay the cost
# of establishing a PostgreSQL connection.
DATABASES["default"]["CONN_MAX_AGE"] = 60
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------------
# Static / Media
# ---------------------------------------------------------------------------

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# ---------------------------------------------------------------------------
# OpenAPI / Swagger
# ---------------------------------------------------------------------------

SPECTACULAR_SETTINGS = {
    "TITLE": "OmniChat API",
    "DESCRIPTION": "AI Chat and Knowledge Assistant API",
    "VERSION": "1.0.0",
}


# ---------------------------------------------------------------------------
# AI Configuration
# ---------------------------------------------------------------------------

AI_PROVIDER = env(
    "AI_PROVIDER",
    default="fake",
)

AI_MODEL = env(
    "AI_MODEL",
    default="fake-model",
)

OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
OPENAI_BASE_URL = env(
    "OPENAI_BASE_URL",
    default="https://api.openai.com/v1",
)

OPENAI_READ_TIMEOUT = env.float(
    "OPENAI_READ_TIMEOUT",
    default=30.0,
)

AI_CONTEXT_MAX_TOKENS = env(
    "AI_CONTEXT_MAX_TOKENS",
    default=4000,
)

# Reduced from 4096 to 512.
#
# OmniChat is a conversational application and does not normally need
# thousands of output tokens for a single response.
AI_MAX_OUTPUT_TOKENS = env(
    "AI_MAX_OUTPUT_TOKENS",
    default=1024,
)

AI_KNOWLEDGE_TOP_K = env(
    "AI_KNOWLEDGE_TOP_K",
    default=5,
)


# ---------------------------------------------------------------------------
# Ollama Embeddings
# ---------------------------------------------------------------------------

OLLAMA_BASE_URL = env(
    "OLLAMA_BASE_URL",
    default="http://localhost:11434",
)

OLLAMA_EMBEDDING_MODEL = env(
    "OLLAMA_EMBEDDING_MODEL",
    default="bge-m3",
)

OLLAMA_EMBEDDING_DIMENSIONS = env(
    "OLLAMA_EMBEDDING_DIMENSIONS",
    default=1024,
)

EMBEDDING_PROVIDER = env(
    "EMBEDDING_PROVIDER",
    default="ollama",
)

HF_TOKEN = env(
    "HF_TOKEN",
    default="",
)

HF_EMBEDDING_BASE_URL = env(
    "HF_EMBEDDING_BASE_URL",
    default="https://router.huggingface.co/hf-inference/models",
)

HF_EMBEDDING_MODEL = env(
    "HF_EMBEDDING_MODEL",
    default="Qwen/Qwen3-Embedding-0.6B",
)

HF_EMBEDDING_DIMENSIONS = env.int(
    "HF_EMBEDDING_DIMENSIONS",
    default=1024,
)

# ---------------------------------------------------------------------------
# FreeLLMAPI
# ---------------------------------------------------------------------------

FREELLMAPI_BASE_URL = env(
    "FREELLMAPI_BASE_URL",
    default="http://localhost:3001/v1",
)

FREELLMAPI_API_KEY = env(
    "FREELLMAPI_API_KEY",
    default="",
)

FREELLMAPI_READ_TIMEOUT = env.float(
    "FREELLMAPI_READ_TIMEOUT",
    default=25.0,
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": (
                "{asctime} {levelname} {name} {message}"
            ),
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },

    "loggers": {
        "knowledge.embeddings": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "knowledge.search_service": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "ai.gateway": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "ai.providers.freellmapi": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------------
# Knowledge / Documents
# ---------------------------------------------------------------------------

KNOWLEDGE_MAX_FILE_SIZE = env(
    "KNOWLEDGE_MAX_FILE_SIZE",
    default=10 * 1024 * 1024,
)

KNOWLEDGE_SEARCH_MAX_DISTANCE = env(
    "KNOWLEDGE_SEARCH_MAX_DISTANCE",
    default=0.35,
)


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------

CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL",
    default="redis://127.0.0.1:6379/0",
)

CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    default="redis://127.0.0.1:6379/0",
)

CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60

CELERY_TASK_ALWAYS_EAGER = env.bool(
    "CELERY_TASK_ALWAYS_EAGER",
    default=False,
)

# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[],
)


# Cloudflare R2 object storage
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": env("R2_ACCESS_KEY_ID"),
            "secret_key": env("R2_SECRET_ACCESS_KEY"),
            "endpoint_url": env("R2_ENDPOINT"),
            "bucket_name": env("R2_BUCKET_NAME"),
            "region_name": env("R2_REGION", default="auto"),
            "default_acl": None,
            "file_overwrite": False,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
