# Generated by Django 5.2.17 on 2026-09-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message'),
        ('knowledge', '0005_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sources', to='knowledge.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sources', to='knowledge.document')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='conversations.message')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
