# Generated by Django 5.2.17 on 2026-08-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
