# Generated by Django 5.2.17 on 2026-08-31 03:14

from django.db import migrations
from pgvector.django import VectorExtension, VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_documentchunk"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=VectorField(
                blank=True,
                dimensions=1024,
                null=True,
            ),
        ),
    ]